# Generated by Django 2.2 on 2019-04-27 09:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=False)),
                ('site_name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('period', models.CharField(max_length=20)),
                ('spider_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Spider',
                'verbose_name_plural': 'Spiders',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='SpiderJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='name')),
                ('callable', models.CharField(max_length=2048, verbose_name='callable')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('queue', models.CharField(max_length=16, verbose_name='queue')),
                ('job_id', models.CharField(blank=True, editable=False, max_length=128, null=True, verbose_name='job id')),
                ('timeout', models.IntegerField(blank=True, help_text="Timeout specifies the maximum runtime, in seconds, for the job before it'll be considered 'lost'. Blank uses the default timeout.", null=True, verbose_name='timeout')),
                ('result_ttl', models.IntegerField(blank=True, help_text='The TTL value (in seconds) of the job result. -1: Result never expires, you should delete jobs manually. 0: Result gets deleted immediately. >0: Result expires after n seconds.', null=True, verbose_name='result ttl')),
                ('error_message', models.CharField(max_length=250)),
                ('error_code', models.CharField(max_length=10)),
                ('result', models.PositiveIntegerField(default=0)),
                ('spider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jobs', to='spiders.Spider')),
            ],
            options={
                'verbose_name': 'Spider Job',
                'verbose_name_plural': 'Spider Jobs',
                'ordering': ('name',),
            },
        ),
    ]
